name: mcmd
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10.*
  - pip
  - jupyter
  - jupyterlab
  - numpy
  - scipy
  - pandas
  - ase
  - gemmi
  - pymatgen
  - tqdm
  - simplejson
  - mkl
  - mkl-devel
  - mkl-static
  - mkl-include
  - cython
  - molmod
  - cuda
  - cudatoolkit
  - cudnn
  - pytorch
  - pytorch-cuda
  - torchvision
  - torchaudio
  - pip:
    - CoolProp
    - deepmd-kit[cpu]
    - nequip=0.6.2